# Generated by Django 4.2.8 on 2024-02-09 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """T"""

    initial = True

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shift_number",
                    models.CharField(
                        choices=[
                            ("1st", "1st Shift"),
                            ("2nd", "2nd Shift"),
                            ("3rd", "3rd Shift"),
                            ("4th", "4th Shift"),
                        ],
                        max_length=10,
                    ),
                ),
                ("hours_gone", models.IntegerField()),
                ("absence_type", models.CharField(max_length=50)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_forms",
                        to="login.employee",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filled_forms",
                        to="login.employee",
                    ),
                ),
            ],
        ),
    ]
