# Generated by Django 3.2.23 on 2024-02-12 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absencerequest",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                db_column="approval_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_forms",
                to="login.employee",
            ),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="filled_by",
            field=models.ForeignKey(
                blank=True,
                db_column="filled_by_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filled_forms",
                to="login.employee",
            ),
        ),
        migrations.AlterModelTable(
            name="absencerequest",
            table="forms_absencerequest",
        ),
    ]
