# Generated by Django 4.2.8 on 2024-02-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0002_auto_20240211_1853"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsentDaysAllowed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shiftDay", models.DateField(unique=True)),
                ("allowedAbsent", models.IntegerField(default=0)),
            ],
        ),
    ]
