# Generated by Django 4.2.8 on 2024-02-14 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0003_absentdaysallowed"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="absencerequest",
            table="forms_absence_request",
        ),
        migrations.AlterModelTable(
            name="absentdaysallowed",
            table="absent_days_allowed",
        ),
    ]
