# Generated by Django 4.2.8 on 2024-02-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0004_alter_absencerequest_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="absencerequest",
            name="clock_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
