# Generated by Django 4.2.10 on 2024-02-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_absencerequest_clock_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absencerequest",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
