# Generated by Django 4.2.10 on 2024-03-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_alter_absencerequest_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="absencerequest",
            name="workflow_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A JSON field to store a list of integers.",
                null=True,
            ),
        ),
    ]
