# Generated by Django 4.2.8 on 2024-03-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_workorder_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPDFs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
            options={
                'db_table': 'job_posting_pdfs',
            },
        ),
    ]
