# Generated by Django 4.2.8 on 2024-03-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0009_jobpdfs"),
    ]

    operations = [
        migrations.AddField(
            model_name="absencerequest",
            name="email_address",
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
