# Generated by Django 5.0.2 on 2024-03-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_travelauthorization'),
        ('forms', '0011_jobpdfs_date_created'),
    ]

    operations = [
    ]
