# Generated by Django 5.0.2 on 2024-03-26 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_merge_20240325_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelauthorization',
            name='airfare',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='travelauthorization',
            name='car_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='travelauthorization',
            name='company_car',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='travelauthorization',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='travelauthorization',
            name='personal_car',
            field=models.BooleanField(default=False),
        ),
    ]
