version: '3.8'

services:
  web:
    build: .  # Indicates the current directory, which is 003_MAGNA
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/  # Maps the current directory to /usr/src/app/ inside the container
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
