# Generated by Django 5.0.2 on 2024-02-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('manager_review', 'Manager Review'), ('HR_review', 'HR Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
            ],
        ),
    ]
