# Generated by Django 5.0.2 on 2024-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormEmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=100, unique=True)),
                ('email_recipients', models.TextField(help_text='Comma-separated list of email addresses')),
            ],
        ),
    ]
