# Generated by Django 5.0.2 on 2024-02-28 18:56

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_kiosk1_user(apps, schema_editor):
    Employee = apps.get_model('login', 'Employee')
    Employee.objects.create(username='Kiosk1', password=make_password('freestand1'))


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0002_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(create_kiosk1_user),
    ]
