name: Deploy to Heroku

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.2.2", "1.7.1"]
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pip install poetry==${{ matrix.poetry-version }}
    - name: Install dependencies
      run: |
        poetry install
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        buildpacks: 'https://github.com/moneymeets/python-poetry-buildpack.git heroku/python'
